name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          if [ -d /Users/client/Documents/Dev/MaX/libs/paycom_async ]; then pip install -e /Users/client/Documents/Dev/MaX/libs/paycom_async || true; fi
      - name: Run pytest
        run: |
          if [ -d backend/tests ]; then pytest -q backend/tests; else echo "No backend tests"; fi


